### ISSUE TITLE
Константные параметры для besc_tracepoint()

### ISSUE THREAD

**Issue by AntonKozlov** [AntonKozlov/besc#6]

**Comment by nikitavlaev** [comment]
Ссылки из зума:
https://stackoverflow.com/questions/43500511/how-to-get-the-arguments-of-a-function-call-in-llvm 
https://llvm.org/doxygen/classllvm_1_1CallInst.html 
https://stackoverflow.com/questions/50818343/get-global-string-value-in-llvm 
https://llvm.org/doxygen/classllvm_1_1ConstantDataSequential.html 
https://llvm.org/doxygen/classllvm_1_1opt_1_1ArgList.html#a1ff04e4334977f5f30d63001cb2eb5bb 
https://llvm.org/docs/ProgrammersManual.html#the-isa-cast-and-dyn-cast-templates 
https://llvm.org/doxygen/classllvm_1_1CallBase.html#ab2caa29167597390ab2fc3cf30d70389
