### ISSUE TITLE
Продолжение улучшений алгоритма прохода

### ISSUE THREAD

**Issue by AntonKozlov** [AntonKozlov/besc#7]
Сделать ревью: архитектура, алгоритм, код.

Возможно ли сократить количество проходов для упрощения.

Возможно ли обобщить dfs (не иметь несколько копий алгоритма)?

**Comment by nikitavlaev** [comment]
Можно ли упростить код? Сделать надежнее?
Есть ли тесты, на которых не работает алгоритм?
Поправить код
